.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FWULPATCH" "1" "September 2017" "" ""
.
.SH "NAME"
\fBfwulpatch\fR \- FWUL aims to be an easy to use Android User Linux
.
.SH "DESCRIPTION"
This package provides additional patches/fixes for a released FWUL major version\. Sometimes it is useful to provide just a hotfix for the persistent FWUL releases so not a full ISO has to be downloaded and re\-flashed\.
.
.P
Hint: Using forgetful mode means you have to re\-apply patches on every boot manually!
.
.SH "AUTHOR"
steadfasterX <steadfastX | boun\.cr>
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
FWUL on XDA \fIhttps://tinyurl\.com/FWULatXDA\fR
.
.IP "\(bu" 4
FWUL on github \fIhttps://github\.com/Carbon\-user/build_fwul\fR
.
.IP "" 0

